# Generated by Django 5.0.6 on 2024-07-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تگ')),
                ('url_title', models.CharField(max_length=100, verbose_name='آدرس در مرورگر')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='ChildProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=100, verbose_name='آدرس در مرورگر')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.parentproductcategory', verbose_name='دسته بندی مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی فرزند',
                'verbose_name_plural': 'دسته بندی های فرزند',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('des', models.TextField(max_length=1000, null=True, verbose_name='توضیحات')),
                ('off', models.IntegerField(verbose_name='مقدار تخفیف')),
                ('is_active', models.BooleanField(verbose_name='فعال باشد/نباشد')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس محصول در مرورگر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.childproductcategory', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(to='product_module.producttags', verbose_name='تگ های مربوطه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
