# Generated by Django 5.0.6 on 2024-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='create_date',
            field=models.DateField(default='', verbose_name='زمان ساخته شدن محصول'),
        ),
    ]
