# Generated by Django 5.0.6 on 2024-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('read_by_admin', models.BooleanField(verbose_name='خوانده شده/نشده')),
            ],
            options={
                'verbose_name': 'مجصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
