# Generated by Django 5.0.6 on 2024-07-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_model',
            options={'verbose_name': 'پیغام', 'verbose_name_plural': 'پیغام ها'},
        ),
        migrations.AlterField(
            model_name='contact_model',
            name='read_by_admin',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
